### ISSUE TITLE
Status about the site and infrastructure is unreachable

### ISSUE THREAD

**Issue by IceNinjaman** [callofduty4x/CoD4x_Client_pub#1]
As you all know the site cod4x.me is down and not reachable. It isn't the case I have given up onto the project. Just the domain is expired on the domain registrar. Normally I would just renew the domain. However it isn't going to work as usual. The domain registrar has added 2-factor authentication for sign in, asking for a code he sends in an email. However the email account (powered by Google) can not be accessed by me anymore although I have all the informations like username and password. Basically Google says I hack the account and they don't let me in. Also the deny account recovery by saying they don't have ever got enough information to do any account recovery.
So at this point I can only wait in hope it does maybe get accessible again for me. Only Google knows if I can access it maybe again at a later time. Losing the domain entirely would have terrible consequences as the whole update system does reley onto it.

**Comment by mhwh-dev** [comment]
Hello comrade!
How can you speed up this process, maybe you need help with this problem?

You can also rewrite the client and server, transfer everything to a new domain. It is clear that on average there is a lot of work.
The users often update the client patch and server patch, we don't think it will cause much complication.
Many already offer help in this matter.
Domains are not a problem now, there are plenty of them for every taste.

It's just that if you dwell on this issue for a long time, the community will start to get lost.

I am sorry if I said something wrong. My English is bad!))
